# Generated by Django 5.1 on 2024-10-17 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SaleVolume',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_of_sale', models.CharField(choices=[('FIX', 'F'), ('PERCENT', 'P'), ('GIFT', 'G')], max_length=9)),
                ('value_of_sale', models.FloatField()),
                ('gift_iico_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserIICO',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UsersFilter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=200)),
                ('start_age', models.IntegerField()),
                ('end_age', models.IntegerField()),
                ('sex', models.CharField(choices=[('Мужской', 'm'), ('Женский', 'f'), ('Не задано', 'all')], max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('descryption', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('in_day_start_time', models.TimeField()),
                ('in_day_end_time', models.TimeField()),
                ('start_cost', models.FloatField()),
                ('end_cost', models.FloatField()),
                ('delivery_variant', models.CharField(choices=[('Самовывоз', 's'), ('Даставка', 'd'), ('Не задано', 'all')], max_length=9)),
                ('payment_variant', models.CharField(choices=[('Наличными', 'cash'), ('По карте', 'card'), ('Не задано', 'all')], max_length=9)),
                ('positions', models.ManyToManyField(to='sale.position')),
                ('users_filter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sale.usersfilter')),
            ],
        ),
    ]
