# Generated by Django 5.1 on 2024-10-21 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_remove_salevolume_gift_iico_id_sale_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='users',
        ),
        migrations.AddField(
            model_name='promo',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='sale.useriico'),
        ),
    ]
