# Generated by Django 5.1 on 2024-10-21 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_remove_promo_users_promo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sale.sale', verbose_name='Тип скидки'),
        ),
        migrations.RemoveField(
            model_name='promo',
            name='user',
        ),
        migrations.AlterField(
            model_name='sale',
            name='delivery_variant',
            field=models.CharField(choices=[('s', 'Самовывоз'), ('d', 'Даставка'), ('all', 'Не задано')], max_length=9, verbose_name='Вариант доставки'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='descryption',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='end_cost',
            field=models.FloatField(default=1000000000000, help_text='Акция действует, если стоимость заказа меньше указанной', verbose_name='Конечная стоимость'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания акции'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='in_day_end_time',
            field=models.TimeField(verbose_name='Время окончания акции'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='in_day_start_time',
            field=models.TimeField(help_text='Акция действует в течении выбранного периода времени ежедневно. Следует указать временные рамки действия акции в течение дня', verbose_name='Время начала акции'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_variant',
            field=models.CharField(choices=[('cash', 'Наличными'), ('card', 'По карте'), ('online', 'Онлайн'), ('all', 'Не задано')], max_length=9, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='positions',
            field=models.ManyToManyField(help_text='Выбор позиций, на которые распространяется акция', to='sale.position', verbose_name='Позиции меню'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.salevolume', verbose_name='Тип скидки'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='start_cost',
            field=models.FloatField(default=0, help_text='Акция действует, если стоимость заказа больше указанной', verbose_name='Начальная стоимость'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала акции'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='users_filter',
            field=models.OneToOneField(help_text='Выбор группы пользователей по поло-возрастному признаку, либо конкретного пользователя', on_delete=django.db.models.deletion.CASCADE, to='sale.usersfilter', verbose_name='Пользовательский фильтр'),
        ),
        migrations.AlterField(
            model_name='salevolume',
            name='gift_position',
            field=models.ManyToManyField(help_text='Заполнять только если выбран вид скидки - "Подарок"', null=True, to='sale.position', verbose_name='Блюдо в подарок'),
        ),
        migrations.AlterField(
            model_name='salevolume',
            name='type_of_sale',
            field=models.CharField(choices=[('F', 'Фиксированаая'), ('P', 'В процентах'), ('G', 'Подарок')], max_length=1, verbose_name='Вид скидки'),
        ),
        migrations.AlterField(
            model_name='salevolume',
            name='value_of_sale',
            field=models.FloatField(verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='usersfilter',
            name='end_age',
            field=models.IntegerField(default=150, verbose_name='Максимальный возраст'),
        ),
        migrations.AlterField(
            model_name='usersfilter',
            name='sex',
            field=models.CharField(choices=[('m', 'Мужской'), ('f', 'Женский'), ('all', 'Не задано')], max_length=9, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='usersfilter',
            name='start_age',
            field=models.IntegerField(default=0, verbose_name='Начальный возраст'),
        ),
        migrations.AlterField(
            model_name='usersfilter',
            name='user_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='user',
            field=models.ManyToManyField(default=None, to='sale.useriico', verbose_name='Пользователи'),
        ),
    ]
