# Generated by Django 5.1 on 2024-10-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_alter_sale_delivery_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salevolume',
            name='title',
            field=models.CharField(max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='usersfilter',
            name='user_id',
            field=models.CharField(default='all', help_text='Если скидка не индивидуальная НЕ меняйте значение поля!', max_length=200, null=True, verbose_name='Выбор id пользователя'),
        ),
    ]
