# Generated by Django 5.1 on 2024-10-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_salevolume_title_alter_usersfilter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useriico',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='useriico',
            name='sex',
            field=models.CharField(choices=[('m', 'Мужской'), ('f', 'Женский'), ('all', 'Не задано')], default='all', max_length=9, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='salevolume',
            name='gift_position',
            field=models.ManyToManyField(blank=True, help_text='Заполнять только если выбран вид скидки - "Подарок"', null=True, to='sale.position', verbose_name='Блюдо в подарок'),
        ),
    ]
